/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Keys;
import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.AddressMetroStationRecord;


/**
 * Contains relation address - metro station
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressMetroStation extends TableImpl<AddressMetroStationRecord> {

    private static final long serialVersionUID = 1657728409;

    /**
     * The reference instance of <code>public.address_metro_station</code>
     */
    public static final AddressMetroStation ADDRESS_METRO_STATION = new AddressMetroStation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AddressMetroStationRecord> getRecordType() {
        return AddressMetroStationRecord.class;
    }

    /**
     * The column <code>public.address_metro_station.address_id</code>.
     */
    public final TableField<AddressMetroStationRecord, Integer> ADDRESS_ID = createField("address_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.address_metro_station.metro_station_id</code>.
     */
    public final TableField<AddressMetroStationRecord, Integer> METRO_STATION_ID = createField("metro_station_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.address_metro_station</code> table reference
     */
    public AddressMetroStation() {
        this("address_metro_station", null);
    }

    /**
     * Create an aliased <code>public.address_metro_station</code> table reference
     */
    public AddressMetroStation(String alias) {
        this(alias, ADDRESS_METRO_STATION);
    }

    private AddressMetroStation(String alias, Table<AddressMetroStationRecord> aliased) {
        this(alias, aliased, null);
    }

    private AddressMetroStation(String alias, Table<AddressMetroStationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "Contains relation address - metro station");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AddressMetroStationRecord> getPrimaryKey() {
        return Keys.ADDRESS_METRO_STATION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AddressMetroStationRecord>> getKeys() {
        return Arrays.<UniqueKey<AddressMetroStationRecord>>asList(Keys.ADDRESS_METRO_STATION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AddressMetroStationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AddressMetroStationRecord, ?>>asList(Keys.ADDRESS_METRO_STATION__ADDRESS_METRO_STATION_TO_ADDRESS_FK, Keys.ADDRESS_METRO_STATION__ADDRESS_METRO_STATION_TO_METRO_STATION_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressMetroStation as(String alias) {
        return new AddressMetroStation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AddressMetroStation rename(String name) {
        return new AddressMetroStation(name, null);
    }
}
