/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Keys;
import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.AgreementStateRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgreementState extends TableImpl<AgreementStateRecord> {

    private static final long serialVersionUID = -574996053;

    /**
     * The reference instance of <code>public.agreement_state</code>
     */
    public static final AgreementState AGREEMENT_STATE = new AgreementState();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AgreementStateRecord> getRecordType() {
        return AgreementStateRecord.class;
    }

    /**
     * The column <code>public.agreement_state.agreement_state_id</code>.
     */
    public final TableField<AgreementStateRecord, Integer> AGREEMENT_STATE_ID = createField("agreement_state_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('agreement_state_agreement_state_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.agreement_state.name</code>.
     */
    public final TableField<AgreementStateRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.agreement_state.can_edit_vfs_file</code>.
     */
    public final TableField<AgreementStateRecord, Boolean> CAN_EDIT_VFS_FILE = createField("can_edit_vfs_file", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>public.agreement_state</code> table reference
     */
    public AgreementState() {
        this("agreement_state", null);
    }

    /**
     * Create an aliased <code>public.agreement_state</code> table reference
     */
    public AgreementState(String alias) {
        this(alias, AGREEMENT_STATE);
    }

    private AgreementState(String alias, Table<AgreementStateRecord> aliased) {
        this(alias, aliased, null);
    }

    private AgreementState(String alias, Table<AgreementStateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AgreementStateRecord, Integer> getIdentity() {
        return Keys.IDENTITY_AGREEMENT_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AgreementStateRecord> getPrimaryKey() {
        return Keys.AGREEMENT_STATE_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AgreementStateRecord>> getKeys() {
        return Arrays.<UniqueKey<AgreementStateRecord>>asList(Keys.AGREEMENT_STATE_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgreementState as(String alias) {
        return new AgreementState(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AgreementState rename(String name) {
        return new AgreementState(name, null);
    }
}
