/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Keys;
import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.ApplicantCareerGuidanceHistoryRecord;


/**
 * История изменений по сервису профориентация. Таблица insert only
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplicantCareerGuidanceHistory extends TableImpl<ApplicantCareerGuidanceHistoryRecord> {

    private static final long serialVersionUID = 590278133;

    /**
     * The reference instance of <code>public.applicant_career_guidance_history</code>
     */
    public static final ApplicantCareerGuidanceHistory APPLICANT_CAREER_GUIDANCE_HISTORY = new ApplicantCareerGuidanceHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ApplicantCareerGuidanceHistoryRecord> getRecordType() {
        return ApplicantCareerGuidanceHistoryRecord.class;
    }

    /**
     * The column <code>public.applicant_career_guidance_history.history_id</code>.
     */
    public final TableField<ApplicantCareerGuidanceHistoryRecord, Integer> HISTORY_ID = createField("history_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('applicant_career_guidance_history_history_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.applicant_career_guidance_history.activation_code</code>.
     */
    public final TableField<ApplicantCareerGuidanceHistoryRecord, Integer> ACTIVATION_CODE = createField("activation_code", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.applicant_career_guidance_history.activation_date</code>.
     */
    public final TableField<ApplicantCareerGuidanceHistoryRecord, LocalDateTime> ACTIVATION_DATE = createField("activation_date", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>public.applicant_career_guidance_history.user_id</code>.
     */
    public final TableField<ApplicantCareerGuidanceHistoryRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.applicant_career_guidance_history.site_id</code>.
     */
    public final TableField<ApplicantCareerGuidanceHistoryRecord, Integer> SITE_ID = createField("site_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.applicant_career_guidance_history.lang</code>.
     */
    public final TableField<ApplicantCareerGuidanceHistoryRecord, String> LANG = createField("lang", org.jooq.impl.SQLDataType.VARCHAR.length(2), this, "");

    /**
     * The column <code>public.applicant_career_guidance_history.uid</code>.
     */
    public final TableField<ApplicantCareerGuidanceHistoryRecord, String> UID = createField("uid", org.jooq.impl.SQLDataType.VARCHAR.length(37), this, "");

    /**
     * The column <code>public.applicant_career_guidance_history.status</code>.
     */
    public final TableField<ApplicantCareerGuidanceHistoryRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.applicant_career_guidance_history.activated_by_user_id</code>.
     */
    public final TableField<ApplicantCareerGuidanceHistoryRecord, Integer> ACTIVATED_BY_USER_ID = createField("activated_by_user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.applicant_career_guidance_history.activation_uid</code>.
     */
    public final TableField<ApplicantCareerGuidanceHistoryRecord, String> ACTIVATION_UID = createField("activation_uid", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>public.applicant_career_guidance_history.last_update_date</code>.
     */
    public final TableField<ApplicantCareerGuidanceHistoryRecord, LocalDateTime> LAST_UPDATE_DATE = createField("last_update_date", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.applicant_career_guidance_history.testing_status</code>.
     */
    public final TableField<ApplicantCareerGuidanceHistoryRecord, Integer> TESTING_STATUS = createField("testing_status", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("8", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>public.applicant_career_guidance_history</code> table reference
     */
    public ApplicantCareerGuidanceHistory() {
        this("applicant_career_guidance_history", null);
    }

    /**
     * Create an aliased <code>public.applicant_career_guidance_history</code> table reference
     */
    public ApplicantCareerGuidanceHistory(String alias) {
        this(alias, APPLICANT_CAREER_GUIDANCE_HISTORY);
    }

    private ApplicantCareerGuidanceHistory(String alias, Table<ApplicantCareerGuidanceHistoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private ApplicantCareerGuidanceHistory(String alias, Table<ApplicantCareerGuidanceHistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "История изменений по сервису профориентация. Таблица insert only");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ApplicantCareerGuidanceHistoryRecord, Integer> getIdentity() {
        return Keys.IDENTITY_APPLICANT_CAREER_GUIDANCE_HISTORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ApplicantCareerGuidanceHistoryRecord> getPrimaryKey() {
        return Keys.APPLICANT_CAREER_GUIDANCE_HISTORY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ApplicantCareerGuidanceHistoryRecord>> getKeys() {
        return Arrays.<UniqueKey<ApplicantCareerGuidanceHistoryRecord>>asList(Keys.APPLICANT_CAREER_GUIDANCE_HISTORY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ApplicantCareerGuidanceHistoryRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ApplicantCareerGuidanceHistoryRecord, ?>>asList(Keys.APPLICANT_CAREER_GUIDANCE_HISTORY__APPLICANT_CAREER_GUIDANCE_HISTORY_HHUSER_FK, Keys.APPLICANT_CAREER_GUIDANCE_HISTORY__APPLICANT_CAREER_GUIDANCE_HISTORY_SITE_FK, Keys.APPLICANT_CAREER_GUIDANCE_HISTORY__APPLICANT_CAREER_GUIDANCE_HISTORY_ACTIVATED_BY_USER_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicantCareerGuidanceHistory as(String alias) {
        return new ApplicantCareerGuidanceHistory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ApplicantCareerGuidanceHistory rename(String name) {
        return new ApplicantCareerGuidanceHistory(name, null);
    }
}
