/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Keys;
import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.DigestClientRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DigestClient extends TableImpl<DigestClientRecord> {

    private static final long serialVersionUID = 1549474715;

    /**
     * The reference instance of <code>public.digest_client</code>
     */
    public static final DigestClient DIGEST_CLIENT = new DigestClient();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DigestClientRecord> getRecordType() {
        return DigestClientRecord.class;
    }

    /**
     * The column <code>public.digest_client.name</code>.
     */
    public final TableField<DigestClientRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>public.digest_client.base_url_key</code>.
     */
    public final TableField<DigestClientRecord, String> BASE_URL_KEY = createField("base_url_key", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>public.digest_client</code> table reference
     */
    public DigestClient() {
        this("digest_client", null);
    }

    /**
     * Create an aliased <code>public.digest_client</code> table reference
     */
    public DigestClient(String alias) {
        this(alias, DIGEST_CLIENT);
    }

    private DigestClient(String alias, Table<DigestClientRecord> aliased) {
        this(alias, aliased, null);
    }

    private DigestClient(String alias, Table<DigestClientRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DigestClientRecord> getPrimaryKey() {
        return Keys.DIGEST_CLIENT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DigestClientRecord>> getKeys() {
        return Arrays.<UniqueKey<DigestClientRecord>>asList(Keys.DIGEST_CLIENT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DigestClient as(String alias) {
        return new DigestClient(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DigestClient rename(String name) {
        return new DigestClient(name, null);
    }
}
