/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Keys;
import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.EmployerManagerActivityRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployerManagerActivity extends TableImpl<EmployerManagerActivityRecord> {

    private static final long serialVersionUID = -1137763954;

    /**
     * The reference instance of <code>public.employer_manager_activity</code>
     */
    public static final EmployerManagerActivity EMPLOYER_MANAGER_ACTIVITY = new EmployerManagerActivity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmployerManagerActivityRecord> getRecordType() {
        return EmployerManagerActivityRecord.class;
    }

    /**
     * The column <code>public.employer_manager_activity.employer_manager_activity_id</code>.
     */
    public final TableField<EmployerManagerActivityRecord, Integer> EMPLOYER_MANAGER_ACTIVITY_ID = createField("employer_manager_activity_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('employer_manager_activity_employer_manager_activity_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.employer_manager_activity.hhid</code>.
     */
    public final TableField<EmployerManagerActivityRecord, Long> HHID = createField("hhid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.employer_manager_activity.last_active_time</code>.
     */
    public final TableField<EmployerManagerActivityRecord, LocalDateTime> LAST_ACTIVE_TIME = createField("last_active_time", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>public.employer_manager_activity.employer_id</code>.
     */
    public final TableField<EmployerManagerActivityRecord, Integer> EMPLOYER_ID = createField("employer_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.employer_manager_activity.employer_manager_id</code>.
     */
    public final TableField<EmployerManagerActivityRecord, Integer> EMPLOYER_MANAGER_ID = createField("employer_manager_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.employer_manager_activity</code> table reference
     */
    public EmployerManagerActivity() {
        this("employer_manager_activity", null);
    }

    /**
     * Create an aliased <code>public.employer_manager_activity</code> table reference
     */
    public EmployerManagerActivity(String alias) {
        this(alias, EMPLOYER_MANAGER_ACTIVITY);
    }

    private EmployerManagerActivity(String alias, Table<EmployerManagerActivityRecord> aliased) {
        this(alias, aliased, null);
    }

    private EmployerManagerActivity(String alias, Table<EmployerManagerActivityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EmployerManagerActivityRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EMPLOYER_MANAGER_ACTIVITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EmployerManagerActivityRecord> getPrimaryKey() {
        return Keys.EMPLOYER_MANAGER_ACTIVITY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EmployerManagerActivityRecord>> getKeys() {
        return Arrays.<UniqueKey<EmployerManagerActivityRecord>>asList(Keys.EMPLOYER_MANAGER_ACTIVITY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<EmployerManagerActivityRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<EmployerManagerActivityRecord, ?>>asList(Keys.EMPLOYER_MANAGER_ACTIVITY__EMPLOYER_MANAGER_ACTIVITY_EMPLOYER_ID, Keys.EMPLOYER_MANAGER_ACTIVITY__EMPLOYER_MANAGER_ACTIVITY_EMPLOYER_MANAGER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployerManagerActivity as(String alias) {
        return new EmployerManagerActivity(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmployerManagerActivity rename(String name) {
        return new EmployerManagerActivity(name, null);
    }
}
