/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Keys;
import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.GeneralBankDetailRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeneralBankDetail extends TableImpl<GeneralBankDetailRecord> {

    private static final long serialVersionUID = 159325924;

    /**
     * The reference instance of <code>public.general_bank_detail</code>
     */
    public static final GeneralBankDetail GENERAL_BANK_DETAIL = new GeneralBankDetail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GeneralBankDetailRecord> getRecordType() {
        return GeneralBankDetailRecord.class;
    }

    /**
     * The column <code>public.general_bank_detail.bank_detail_type</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> BANK_DETAIL_TYPE = createField("bank_detail_type", org.jooq.impl.SQLDataType.VARCHAR.length(31).nullable(false), this, "");

    /**
     * The column <code>public.general_bank_detail.bank_detail_id</code>.
     */
    public final TableField<GeneralBankDetailRecord, Integer> BANK_DETAIL_ID = createField("bank_detail_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('general_bank_detail_bank_detail_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.general_bank_detail.company_name</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> COMPANY_NAME = createField("company_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.consignee</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> CONSIGNEE = createField("consignee", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.delivery_person</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> DELIVERY_PERSON = createField("delivery_person", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.org_bd_bank_account</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> ORG_BD_BANK_ACCOUNT = createField("org_bd_bank_account", org.jooq.impl.SQLDataType.VARCHAR.length(20).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.org_bd_bank</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> ORG_BD_BANK = createField("org_bd_bank", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.org_bd_kpp</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> ORG_BD_KPP = createField("org_bd_kpp", org.jooq.impl.SQLDataType.VARCHAR.length(9).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.org_bd_bik</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> ORG_BD_BIK = createField("org_bd_bik", org.jooq.impl.SQLDataType.VARCHAR.length(9).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.org_bd_corr_account</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> ORG_BD_CORR_ACCOUNT = createField("org_bd_corr_account", org.jooq.impl.SQLDataType.VARCHAR.length(40).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.org_bd_corr_account_bank</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> ORG_BD_CORR_ACCOUNT_BANK = createField("org_bd_corr_account_bank", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.org_bd_okpo</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> ORG_BD_OKPO = createField("org_bd_okpo", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.general_bank_detail.org_bd_okonh</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> ORG_BD_OKONH = createField("org_bd_okonh", org.jooq.impl.SQLDataType.VARCHAR.length(64).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.org_bd_edrpou</code>. unused
     */
    public final TableField<GeneralBankDetailRecord, String> ORG_BD_EDRPOU = createField("org_bd_edrpou", org.jooq.impl.SQLDataType.VARCHAR.length(12).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "unused");

    /**
     * The column <code>public.general_bank_detail.org_bd_mfo</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> ORG_BD_MFO = createField("org_bd_mfo", org.jooq.impl.SQLDataType.VARCHAR.length(9).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.org_bd_payer_licence_number</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> ORG_BD_PAYER_LICENCE_NUMBER = createField("org_bd_payer_licence_number", org.jooq.impl.SQLDataType.VARCHAR.length(20).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.org_bd_payer_licence_date</code>.
     */
    public final TableField<GeneralBankDetailRecord, LocalDateTime> ORG_BD_PAYER_LICENCE_DATE = createField("org_bd_payer_licence_date", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.general_bank_detail.org_bd_tax_scheme</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> ORG_BD_TAX_SCHEME = createField("org_bd_tax_scheme", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.pr_bd_firstname</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> PR_BD_FIRSTNAME = createField("pr_bd_firstname", org.jooq.impl.SQLDataType.VARCHAR.length(25).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.pr_bd_middlename</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> PR_BD_MIDDLENAME = createField("pr_bd_middlename", org.jooq.impl.SQLDataType.VARCHAR.length(25).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.pr_bd_lastname</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> PR_BD_LASTNAME = createField("pr_bd_lastname", org.jooq.impl.SQLDataType.VARCHAR.length(25).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.pr_bd_passport_series</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> PR_BD_PASSPORT_SERIES = createField("pr_bd_passport_series", org.jooq.impl.SQLDataType.VARCHAR.length(4).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.pr_bd_passport_number</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> PR_BD_PASSPORT_NUMBER = createField("pr_bd_passport_number", org.jooq.impl.SQLDataType.VARCHAR.length(6).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.pr_bd_passport_gived_organization</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> PR_BD_PASSPORT_GIVED_ORGANIZATION = createField("pr_bd_passport_gived_organization", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.pr_bd_passport_gived_date</code>.
     */
    public final TableField<GeneralBankDetailRecord, LocalDate> PR_BD_PASSPORT_GIVED_DATE = createField("pr_bd_passport_gived_date", org.jooq.impl.SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.general_bank_detail.payer_id</code>.
     */
    public final TableField<GeneralBankDetailRecord, Integer> PAYER_ID = createField("payer_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.general_bank_detail.delivery_address_id</code>.
     */
    public final TableField<GeneralBankDetailRecord, Integer> DELIVERY_ADDRESS_ID = createField("delivery_address_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.general_bank_detail.org_bd_kpp2</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> ORG_BD_KPP2 = createField("org_bd_kpp2", org.jooq.impl.SQLDataType.VARCHAR.length(9).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.general_bank_detail.address</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>public.general_bank_detail.org_bd_ua_inn</code>.
     */
    public final TableField<GeneralBankDetailRecord, String> ORG_BD_UA_INN = createField("org_bd_ua_inn", org.jooq.impl.SQLDataType.VARCHAR.length(12), this, "");

    /**
     * Create a <code>public.general_bank_detail</code> table reference
     */
    public GeneralBankDetail() {
        this("general_bank_detail", null);
    }

    /**
     * Create an aliased <code>public.general_bank_detail</code> table reference
     */
    public GeneralBankDetail(String alias) {
        this(alias, GENERAL_BANK_DETAIL);
    }

    private GeneralBankDetail(String alias, Table<GeneralBankDetailRecord> aliased) {
        this(alias, aliased, null);
    }

    private GeneralBankDetail(String alias, Table<GeneralBankDetailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<GeneralBankDetailRecord, Integer> getIdentity() {
        return Keys.IDENTITY_GENERAL_BANK_DETAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GeneralBankDetailRecord> getPrimaryKey() {
        return Keys.GENERAL_BANK_DETAIL_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GeneralBankDetailRecord>> getKeys() {
        return Arrays.<UniqueKey<GeneralBankDetailRecord>>asList(Keys.GENERAL_BANK_DETAIL_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GeneralBankDetailRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GeneralBankDetailRecord, ?>>asList(Keys.GENERAL_BANK_DETAIL__BANK_DETAIL_PAYER_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GeneralBankDetail as(String alias) {
        return new GeneralBankDetail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GeneralBankDetail rename(String name) {
        return new GeneralBankDetail(name, null);
    }
}
