/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Keys;
import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.HowHearAboutUsAccessibleSitesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HowHearAboutUsAccessibleSites extends TableImpl<HowHearAboutUsAccessibleSitesRecord> {

    private static final long serialVersionUID = -88747320;

    /**
     * The reference instance of <code>public.how_hear_about_us_accessible_sites</code>
     */
    public static final HowHearAboutUsAccessibleSites HOW_HEAR_ABOUT_US_ACCESSIBLE_SITES = new HowHearAboutUsAccessibleSites();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HowHearAboutUsAccessibleSitesRecord> getRecordType() {
        return HowHearAboutUsAccessibleSitesRecord.class;
    }

    /**
     * The column <code>public.how_hear_about_us_accessible_sites.how_hear_about_us_how_hear_about_us_id</code>.
     */
    public final TableField<HowHearAboutUsAccessibleSitesRecord, Integer> HOW_HEAR_ABOUT_US_HOW_HEAR_ABOUT_US_ID = createField("how_hear_about_us_how_hear_about_us_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.how_hear_about_us_accessible_sites.element</code>.
     */
    public final TableField<HowHearAboutUsAccessibleSitesRecord, Integer> ELEMENT = createField("element", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.how_hear_about_us_accessible_sites</code> table reference
     */
    public HowHearAboutUsAccessibleSites() {
        this("how_hear_about_us_accessible_sites", null);
    }

    /**
     * Create an aliased <code>public.how_hear_about_us_accessible_sites</code> table reference
     */
    public HowHearAboutUsAccessibleSites(String alias) {
        this(alias, HOW_HEAR_ABOUT_US_ACCESSIBLE_SITES);
    }

    private HowHearAboutUsAccessibleSites(String alias, Table<HowHearAboutUsAccessibleSitesRecord> aliased) {
        this(alias, aliased, null);
    }

    private HowHearAboutUsAccessibleSites(String alias, Table<HowHearAboutUsAccessibleSitesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<HowHearAboutUsAccessibleSitesRecord>> getKeys() {
        return Arrays.<UniqueKey<HowHearAboutUsAccessibleSitesRecord>>asList(Keys.HOW_HEAR_ABOUT_US_ACCESSIBLE_SITES_HOW_HEAR_ABOUT_US_ID_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HowHearAboutUsAccessibleSites as(String alias) {
        return new HowHearAboutUsAccessibleSites(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public HowHearAboutUsAccessibleSites rename(String name) {
        return new HowHearAboutUsAccessibleSites(name, null);
    }
}
