/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Keys;
import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.ManagerFavoriteFolderRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManagerFavoriteFolder extends TableImpl<ManagerFavoriteFolderRecord> {

    private static final long serialVersionUID = 1649181939;

    /**
     * The reference instance of <code>public.manager_favorite_folder</code>
     */
    public static final ManagerFavoriteFolder MANAGER_FAVORITE_FOLDER = new ManagerFavoriteFolder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ManagerFavoriteFolderRecord> getRecordType() {
        return ManagerFavoriteFolderRecord.class;
    }

    /**
     * The column <code>public.manager_favorite_folder.employer_manager_id</code>.
     */
    public final TableField<ManagerFavoriteFolderRecord, Integer> EMPLOYER_MANAGER_ID = createField("employer_manager_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.manager_favorite_folder.favorite_resume_folder_id</code>.
     */
    public final TableField<ManagerFavoriteFolderRecord, Integer> FAVORITE_RESUME_FOLDER_ID = createField("favorite_resume_folder_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.manager_favorite_folder</code> table reference
     */
    public ManagerFavoriteFolder() {
        this("manager_favorite_folder", null);
    }

    /**
     * Create an aliased <code>public.manager_favorite_folder</code> table reference
     */
    public ManagerFavoriteFolder(String alias) {
        this(alias, MANAGER_FAVORITE_FOLDER);
    }

    private ManagerFavoriteFolder(String alias, Table<ManagerFavoriteFolderRecord> aliased) {
        this(alias, aliased, null);
    }

    private ManagerFavoriteFolder(String alias, Table<ManagerFavoriteFolderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ManagerFavoriteFolderRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ManagerFavoriteFolderRecord, ?>>asList(Keys.MANAGER_FAVORITE_FOLDER__MANAGER_FAVORITE_FOLDER_EMPLOYER_MANAGER_ID_FKEY, Keys.MANAGER_FAVORITE_FOLDER__MANAGER_FAVORITE_FOLDER_FAVORITE_RESUME_FOLDER_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagerFavoriteFolder as(String alias) {
        return new ManagerFavoriteFolder(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ManagerFavoriteFolder rename(String name) {
        return new ManagerFavoriteFolder(name, null);
    }
}
