/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Keys;
import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.ServiceProfessionalAreaRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServiceProfessionalArea extends TableImpl<ServiceProfessionalAreaRecord> {

    private static final long serialVersionUID = 785265168;

    /**
     * The reference instance of <code>public.service_professional_area</code>
     */
    public static final ServiceProfessionalArea SERVICE_PROFESSIONAL_AREA = new ServiceProfessionalArea();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServiceProfessionalAreaRecord> getRecordType() {
        return ServiceProfessionalAreaRecord.class;
    }

    /**
     * The column <code>public.service_professional_area.service_id</code>.
     */
    public final TableField<ServiceProfessionalAreaRecord, Integer> SERVICE_ID = createField("service_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.service_professional_area.professional_area_id</code>.
     */
    public final TableField<ServiceProfessionalAreaRecord, Integer> PROFESSIONAL_AREA_ID = createField("professional_area_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.service_professional_area</code> table reference
     */
    public ServiceProfessionalArea() {
        this("service_professional_area", null);
    }

    /**
     * Create an aliased <code>public.service_professional_area</code> table reference
     */
    public ServiceProfessionalArea(String alias) {
        this(alias, SERVICE_PROFESSIONAL_AREA);
    }

    private ServiceProfessionalArea(String alias, Table<ServiceProfessionalAreaRecord> aliased) {
        this(alias, aliased, null);
    }

    private ServiceProfessionalArea(String alias, Table<ServiceProfessionalAreaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ServiceProfessionalAreaRecord> getPrimaryKey() {
        return Keys.SERVICE_PROFESSIONAL_AREA_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ServiceProfessionalAreaRecord>> getKeys() {
        return Arrays.<UniqueKey<ServiceProfessionalAreaRecord>>asList(Keys.SERVICE_PROFESSIONAL_AREA_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ServiceProfessionalAreaRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ServiceProfessionalAreaRecord, ?>>asList(Keys.SERVICE_PROFESSIONAL_AREA__FKB937F89B2CE46C5F);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceProfessionalArea as(String alias) {
        return new ServiceProfessionalArea(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ServiceProfessionalArea rename(String name) {
        return new ServiceProfessionalArea(name, null);
    }
}
