/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Keys;
import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.SimilarVacanciesBlockUnsubscriptionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SimilarVacanciesBlockUnsubscription extends TableImpl<SimilarVacanciesBlockUnsubscriptionRecord> {

    private static final long serialVersionUID = -1816341764;

    /**
     * The reference instance of <code>public.similar_vacancies_block_unsubscription</code>
     */
    public static final SimilarVacanciesBlockUnsubscription SIMILAR_VACANCIES_BLOCK_UNSUBSCRIPTION = new SimilarVacanciesBlockUnsubscription();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SimilarVacanciesBlockUnsubscriptionRecord> getRecordType() {
        return SimilarVacanciesBlockUnsubscriptionRecord.class;
    }

    /**
     * The column <code>public.similar_vacancies_block_unsubscription.id</code>.
     */
    public final TableField<SimilarVacanciesBlockUnsubscriptionRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('similar_vacancies_block_unsubscription_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.similar_vacancies_block_unsubscription.subscription_id</code>.
     */
    public final TableField<SimilarVacanciesBlockUnsubscriptionRecord, Integer> SUBSCRIPTION_ID = createField("subscription_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.similar_vacancies_block_unsubscription.date</code>.
     */
    public final TableField<SimilarVacanciesBlockUnsubscriptionRecord, LocalDateTime> DATE = createField("date", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>public.similar_vacancies_block_unsubscription.state</code>.
     */
    public final TableField<SimilarVacanciesBlockUnsubscriptionRecord, String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * Create a <code>public.similar_vacancies_block_unsubscription</code> table reference
     */
    public SimilarVacanciesBlockUnsubscription() {
        this("similar_vacancies_block_unsubscription", null);
    }

    /**
     * Create an aliased <code>public.similar_vacancies_block_unsubscription</code> table reference
     */
    public SimilarVacanciesBlockUnsubscription(String alias) {
        this(alias, SIMILAR_VACANCIES_BLOCK_UNSUBSCRIPTION);
    }

    private SimilarVacanciesBlockUnsubscription(String alias, Table<SimilarVacanciesBlockUnsubscriptionRecord> aliased) {
        this(alias, aliased, null);
    }

    private SimilarVacanciesBlockUnsubscription(String alias, Table<SimilarVacanciesBlockUnsubscriptionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SimilarVacanciesBlockUnsubscriptionRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SIMILAR_VACANCIES_BLOCK_UNSUBSCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SimilarVacanciesBlockUnsubscriptionRecord> getPrimaryKey() {
        return Keys.SIMILAR_VACANCIES_BLOCK_UNSUBSCRIPTION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SimilarVacanciesBlockUnsubscriptionRecord>> getKeys() {
        return Arrays.<UniqueKey<SimilarVacanciesBlockUnsubscriptionRecord>>asList(Keys.SIMILAR_VACANCIES_BLOCK_UNSUBSCRIPTION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SimilarVacanciesBlockUnsubscriptionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SimilarVacanciesBlockUnsubscriptionRecord, ?>>asList(Keys.SIMILAR_VACANCIES_BLOCK_UNSUBSCRIPTION__SIMILAR_VACANCIES_BLOCK_UNSUBSCRIPTION_SUBSCRIPTION_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SimilarVacanciesBlockUnsubscription as(String alias) {
        return new SimilarVacanciesBlockUnsubscription(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SimilarVacanciesBlockUnsubscription rename(String name) {
        return new SimilarVacanciesBlockUnsubscription(name, null);
    }
}
