/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.SpecidToDropRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpecidToDrop extends TableImpl<SpecidToDropRecord> {

    private static final long serialVersionUID = 1014801983;

    /**
     * The reference instance of <code>public.specid_to_drop</code>
     */
    public static final SpecidToDrop SPECID_TO_DROP = new SpecidToDrop();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpecidToDropRecord> getRecordType() {
        return SpecidToDropRecord.class;
    }

    /**
     * The column <code>public.specid_to_drop.nextval</code>.
     */
    public final TableField<SpecidToDropRecord, Long> NEXTVAL = createField("nextval", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.specid_to_drop</code> table reference
     */
    public SpecidToDrop() {
        this("specid_to_drop", null);
    }

    /**
     * Create an aliased <code>public.specid_to_drop</code> table reference
     */
    public SpecidToDrop(String alias) {
        this(alias, SPECID_TO_DROP);
    }

    private SpecidToDrop(String alias, Table<SpecidToDropRecord> aliased) {
        this(alias, aliased, null);
    }

    private SpecidToDrop(String alias, Table<SpecidToDropRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpecidToDrop as(String alias) {
        return new SpecidToDrop(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpecidToDrop rename(String name) {
        return new SpecidToDrop(name, null);
    }
}
