/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Keys;
import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.StatementItemBillRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatementItemBill extends TableImpl<StatementItemBillRecord> {

    private static final long serialVersionUID = -1814839551;

    /**
     * The reference instance of <code>public.statement_item_bill</code>
     */
    public static final StatementItemBill STATEMENT_ITEM_BILL = new StatementItemBill();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StatementItemBillRecord> getRecordType() {
        return StatementItemBillRecord.class;
    }

    /**
     * The column <code>public.statement_item_bill.statement_item_id</code>.
     */
    public final TableField<StatementItemBillRecord, Integer> STATEMENT_ITEM_ID = createField("statement_item_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.statement_item_bill.bill_id</code>.
     */
    public final TableField<StatementItemBillRecord, Integer> BILL_ID = createField("bill_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.statement_item_bill</code> table reference
     */
    public StatementItemBill() {
        this("statement_item_bill", null);
    }

    /**
     * Create an aliased <code>public.statement_item_bill</code> table reference
     */
    public StatementItemBill(String alias) {
        this(alias, STATEMENT_ITEM_BILL);
    }

    private StatementItemBill(String alias, Table<StatementItemBillRecord> aliased) {
        this(alias, aliased, null);
    }

    private StatementItemBill(String alias, Table<StatementItemBillRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StatementItemBillRecord> getPrimaryKey() {
        return Keys.STATEMENT_ITEM_BILL_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StatementItemBillRecord>> getKeys() {
        return Arrays.<UniqueKey<StatementItemBillRecord>>asList(Keys.STATEMENT_ITEM_BILL_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatementItemBill as(String alias) {
        return new StatementItemBill(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StatementItemBill rename(String name) {
        return new StatementItemBill(name, null);
    }
}
