/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.SyncLog_2Record;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SyncLog_2 extends TableImpl<SyncLog_2Record> {

    private static final long serialVersionUID = 1205038234;

    /**
     * The reference instance of <code>public.sync_log_2</code>
     */
    public static final SyncLog_2 SYNC_LOG_2 = new SyncLog_2();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SyncLog_2Record> getRecordType() {
        return SyncLog_2Record.class;
    }

    /**
     * The column <code>public.sync_log_2.sync_version</code>.
     */
    public final TableField<SyncLog_2Record, Long> SYNC_VERSION = createField("sync_version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sync_log_2.item_type</code>.
     */
    public final TableField<SyncLog_2Record, String> ITEM_TYPE = createField("item_type", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sync_log_2.item_id</code>.
     */
    public final TableField<SyncLog_2Record, Long> ITEM_ID = createField("item_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sync_log_2.action</code>.
     */
    public final TableField<SyncLog_2Record, String> ACTION = createField("action", org.jooq.impl.SQLDataType.CHAR.length(1).nullable(false), this, "");

    /**
     * The column <code>public.sync_log_2.ctime</code>.
     */
    public final TableField<SyncLog_2Record, LocalDateTime> CTIME = createField("ctime", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * Create a <code>public.sync_log_2</code> table reference
     */
    public SyncLog_2() {
        this("sync_log_2", null);
    }

    /**
     * Create an aliased <code>public.sync_log_2</code> table reference
     */
    public SyncLog_2(String alias) {
        this(alias, SYNC_LOG_2);
    }

    private SyncLog_2(String alias, Table<SyncLog_2Record> aliased) {
        this(alias, aliased, null);
    }

    private SyncLog_2(String alias, Table<SyncLog_2Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SyncLog_2 as(String alias) {
        return new SyncLog_2(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SyncLog_2 rename(String name) {
        return new SyncLog_2(name, null);
    }
}
