/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Keys;
import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.TargetAgencyEmployerRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TargetAgencyEmployer extends TableImpl<TargetAgencyEmployerRecord> {

    private static final long serialVersionUID = 609895349;

    /**
     * The reference instance of <code>public.target_agency_employer</code>
     */
    public static final TargetAgencyEmployer TARGET_AGENCY_EMPLOYER = new TargetAgencyEmployer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TargetAgencyEmployerRecord> getRecordType() {
        return TargetAgencyEmployerRecord.class;
    }

    /**
     * The column <code>public.target_agency_employer.target_agency_employer_id</code>.
     */
    public final TableField<TargetAgencyEmployerRecord, Integer> TARGET_AGENCY_EMPLOYER_ID = createField("target_agency_employer_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('target_agency_employer_target_agency_employer_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.target_agency_employer.resume_target_agencies_id</code>.
     */
    public final TableField<TargetAgencyEmployerRecord, Integer> RESUME_TARGET_AGENCIES_ID = createField("resume_target_agencies_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.target_agency_employer.resume_target_employer_id</code>.
     */
    public final TableField<TargetAgencyEmployerRecord, Integer> RESUME_TARGET_EMPLOYER_ID = createField("resume_target_employer_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.target_agency_employer</code> table reference
     */
    public TargetAgencyEmployer() {
        this("target_agency_employer", null);
    }

    /**
     * Create an aliased <code>public.target_agency_employer</code> table reference
     */
    public TargetAgencyEmployer(String alias) {
        this(alias, TARGET_AGENCY_EMPLOYER);
    }

    private TargetAgencyEmployer(String alias, Table<TargetAgencyEmployerRecord> aliased) {
        this(alias, aliased, null);
    }

    private TargetAgencyEmployer(String alias, Table<TargetAgencyEmployerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TargetAgencyEmployerRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TARGET_AGENCY_EMPLOYER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TargetAgencyEmployerRecord> getPrimaryKey() {
        return Keys.TARGET_AGENCY_EMPLOYER_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TargetAgencyEmployerRecord>> getKeys() {
        return Arrays.<UniqueKey<TargetAgencyEmployerRecord>>asList(Keys.TARGET_AGENCY_EMPLOYER_PKEY, Keys.TARGET_AGENCY_EMPLOYER_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TargetAgencyEmployerRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TargetAgencyEmployerRecord, ?>>asList(Keys.TARGET_AGENCY_EMPLOYER__TARGET_AGENCY_EMPLOYER_AGENCIES_FK, Keys.TARGET_AGENCY_EMPLOYER__TARGET_AGENCY_EMPLOYER_EMPLOYERS_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TargetAgencyEmployer as(String alias) {
        return new TargetAgencyEmployer(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetAgencyEmployer rename(String name) {
        return new TargetAgencyEmployer(name, null);
    }
}
