/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Keys;
import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.VacancySpentServiceAreaScopeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VacancySpentServiceAreaScope extends TableImpl<VacancySpentServiceAreaScopeRecord> {

    private static final long serialVersionUID = 1432375024;

    /**
     * The reference instance of <code>public.vacancy_spent_service_area_scope</code>
     */
    public static final VacancySpentServiceAreaScope VACANCY_SPENT_SERVICE_AREA_SCOPE = new VacancySpentServiceAreaScope();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VacancySpentServiceAreaScopeRecord> getRecordType() {
        return VacancySpentServiceAreaScopeRecord.class;
    }

    /**
     * The column <code>public.vacancy_spent_service_area_scope.vacancy_spent_service_id</code>.
     */
    public final TableField<VacancySpentServiceAreaScopeRecord, Integer> VACANCY_SPENT_SERVICE_ID = createField("vacancy_spent_service_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.vacancy_spent_service_area_scope.area_id</code>.
     */
    public final TableField<VacancySpentServiceAreaScopeRecord, Integer> AREA_ID = createField("area_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.vacancy_spent_service_area_scope.index_</code>.
     */
    public final TableField<VacancySpentServiceAreaScopeRecord, Integer> INDEX_ = createField("index_", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.vacancy_spent_service_area_scope</code> table reference
     */
    public VacancySpentServiceAreaScope() {
        this("vacancy_spent_service_area_scope", null);
    }

    /**
     * Create an aliased <code>public.vacancy_spent_service_area_scope</code> table reference
     */
    public VacancySpentServiceAreaScope(String alias) {
        this(alias, VACANCY_SPENT_SERVICE_AREA_SCOPE);
    }

    private VacancySpentServiceAreaScope(String alias, Table<VacancySpentServiceAreaScopeRecord> aliased) {
        this(alias, aliased, null);
    }

    private VacancySpentServiceAreaScope(String alias, Table<VacancySpentServiceAreaScopeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VacancySpentServiceAreaScopeRecord> getPrimaryKey() {
        return Keys.VACANCY_SPENT_SERVICE_AREA_SCOPE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VacancySpentServiceAreaScopeRecord>> getKeys() {
        return Arrays.<UniqueKey<VacancySpentServiceAreaScopeRecord>>asList(Keys.VACANCY_SPENT_SERVICE_AREA_SCOPE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<VacancySpentServiceAreaScopeRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<VacancySpentServiceAreaScopeRecord, ?>>asList(Keys.VACANCY_SPENT_SERVICE_AREA_SCOPE__VACANCY_SPENT_SERVICE_AREA_SCOPE_VACANCY_SPENT_SERVICE_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VacancySpentServiceAreaScope as(String alias) {
        return new VacancySpentServiceAreaScope(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VacancySpentServiceAreaScope rename(String name) {
        return new VacancySpentServiceAreaScope(name, null);
    }
}
