/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Keys;
import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.VacancyCatalogPageRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VacancyCatalogPage extends TableImpl<VacancyCatalogPageRecord> {

    private static final long serialVersionUID = -1537184469;

    /**
     * The reference instance of <code>public.vacancy_catalog_page</code>
     */
    public static final VacancyCatalogPage VACANCY_CATALOG_PAGE = new VacancyCatalogPage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VacancyCatalogPageRecord> getRecordType() {
        return VacancyCatalogPageRecord.class;
    }

    /**
     * The column <code>public.vacancy_catalog_page.translit</code>.
     */
    public final TableField<VacancyCatalogPageRecord, String> TRANSLIT = createField("translit", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>public.vacancy_catalog_page.nominative_query</code>.
     */
    public final TableField<VacancyCatalogPageRecord, String> NOMINATIVE_QUERY = createField("nominative_query", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>public.vacancy_catalog_page.ablative_query</code>.
     */
    public final TableField<VacancyCatalogPageRecord, String> ABLATIVE_QUERY = createField("ablative_query", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>public.vacancy_catalog_page.genitive_query_plural</code>.
     */
    public final TableField<VacancyCatalogPageRecord, String> GENITIVE_QUERY_PLURAL = createField("genitive_query_plural", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>public.vacancy_catalog_page</code> table reference
     */
    public VacancyCatalogPage() {
        this("vacancy_catalog_page", null);
    }

    /**
     * Create an aliased <code>public.vacancy_catalog_page</code> table reference
     */
    public VacancyCatalogPage(String alias) {
        this(alias, VACANCY_CATALOG_PAGE);
    }

    private VacancyCatalogPage(String alias, Table<VacancyCatalogPageRecord> aliased) {
        this(alias, aliased, null);
    }

    private VacancyCatalogPage(String alias, Table<VacancyCatalogPageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VacancyCatalogPageRecord> getPrimaryKey() {
        return Keys.VACANCY_CATALOG_PAGE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VacancyCatalogPageRecord>> getKeys() {
        return Arrays.<UniqueKey<VacancyCatalogPageRecord>>asList(Keys.VACANCY_CATALOG_PAGE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VacancyCatalogPage as(String alias) {
        return new VacancyCatalogPage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VacancyCatalogPage rename(String name) {
        return new VacancyCatalogPage(name, null);
    }
}
