/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.hh.jooq.Keys;
import ru.hh.jooq.Public;
import ru.hh.jooq.tables.records.VacancySpentServiceRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VacancySpentService extends TableImpl<VacancySpentServiceRecord> {

    private static final long serialVersionUID = -2112766522;

    /**
     * The reference instance of <code>public.vacancy_spent_service</code>
     */
    public static final VacancySpentService VACANCY_SPENT_SERVICE = new VacancySpentService();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VacancySpentServiceRecord> getRecordType() {
        return VacancySpentServiceRecord.class;
    }

    /**
     * The column <code>public.vacancy_spent_service.id</code>.
     */
    public final TableField<VacancySpentServiceRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('vacancy_spent_service_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.vacancy_spent_service.service_id</code>.
     */
    public final TableField<VacancySpentServiceRecord, Integer> SERVICE_ID = createField("service_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.vacancy_spent_service.ticket_uid</code>.
     */
    public final TableField<VacancySpentServiceRecord, Long> TICKET_UID = createField("ticket_uid", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.vacancy_spent_service.vacancy_id</code>.
     */
    public final TableField<VacancySpentServiceRecord, Integer> VACANCY_ID = createField("vacancy_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.vacancy_spent_service.manager_id</code>.
     */
    public final TableField<VacancySpentServiceRecord, Integer> MANAGER_ID = createField("manager_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.vacancy_spent_service.region</code>.
     */
    public final TableField<VacancySpentServiceRecord, Integer> REGION = createField("region", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.vacancy_spent_service.code</code>.
     */
    public final TableField<VacancySpentServiceRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.length(225), this, "");

    /**
     * Create a <code>public.vacancy_spent_service</code> table reference
     */
    public VacancySpentService() {
        this("vacancy_spent_service", null);
    }

    /**
     * Create an aliased <code>public.vacancy_spent_service</code> table reference
     */
    public VacancySpentService(String alias) {
        this(alias, VACANCY_SPENT_SERVICE);
    }

    private VacancySpentService(String alias, Table<VacancySpentServiceRecord> aliased) {
        this(alias, aliased, null);
    }

    private VacancySpentService(String alias, Table<VacancySpentServiceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<VacancySpentServiceRecord, Integer> getIdentity() {
        return Keys.IDENTITY_VACANCY_SPENT_SERVICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VacancySpentServiceRecord> getPrimaryKey() {
        return Keys.VACANCY_SPENT_SERVICE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VacancySpentServiceRecord>> getKeys() {
        return Arrays.<UniqueKey<VacancySpentServiceRecord>>asList(Keys.VACANCY_SPENT_SERVICE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VacancySpentService as(String alias) {
        return new VacancySpentService(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VacancySpentService rename(String name) {
        return new VacancySpentService(name, null);
    }
}
