/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hh.jooq.tables.BillBillLabel;


/**
 * Auxiliary table to store many-to-many association of bills and bill labels
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BillBillLabelRecord extends UpdatableRecordImpl<BillBillLabelRecord> implements Record3<Integer, Integer, Long> {

    private static final long serialVersionUID = -89331294;

    /**
     * Setter for <code>public.bill_bill_label.bill_id</code>.
     */
    public void setBillId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bill_bill_label.bill_id</code>.
     */
    public Integer getBillId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.bill_bill_label.bill_label_id</code>.
     */
    public void setBillLabelId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bill_bill_label.bill_label_id</code>.
     */
    public Integer getBillLabelId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.bill_bill_label.price</code>.
     */
    public void setPrice(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.bill_bill_label.price</code>.
     */
    public Long getPrice() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return BillBillLabel.BILL_BILL_LABEL.BILL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return BillBillLabel.BILL_BILL_LABEL.BILL_LABEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return BillBillLabel.BILL_BILL_LABEL.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBillId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getBillLabelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillBillLabelRecord value1(Integer value) {
        setBillId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillBillLabelRecord value2(Integer value) {
        setBillLabelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillBillLabelRecord value3(Long value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillBillLabelRecord values(Integer value1, Integer value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BillBillLabelRecord
     */
    public BillBillLabelRecord() {
        super(BillBillLabel.BILL_BILL_LABEL);
    }

    /**
     * Create a detached, initialised BillBillLabelRecord
     */
    public BillBillLabelRecord(Integer billId, Integer billLabelId, Long price) {
        super(BillBillLabel.BILL_BILL_LABEL);

        set(0, billId);
        set(1, billLabelId);
        set(2, price);
    }
}
