/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hh.jooq.tables.CollateralAgreement;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollateralAgreementRecord extends UpdatableRecordImpl<CollateralAgreementRecord> implements Record8<Integer, Integer, String, String, LocalDateTime, Integer, Integer, Integer> {

    private static final long serialVersionUID = 640850409;

    /**
     * Setter for <code>public.collateral_agreement.collateral_agreement_id</code>.
     */
    public void setCollateralAgreementId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.collateral_agreement.collateral_agreement_id</code>.
     */
    public Integer getCollateralAgreementId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.collateral_agreement.agreement_id</code>.
     */
    public void setAgreementId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.collateral_agreement.agreement_id</code>.
     */
    public Integer getAgreementId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.collateral_agreement.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.collateral_agreement.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.collateral_agreement.comment</code>.
     */
    public void setComment(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.collateral_agreement.comment</code>.
     */
    public String getComment() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.collateral_agreement.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.collateral_agreement.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.collateral_agreement.vfs_file_id</code>.
     */
    public void setVfsFileId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.collateral_agreement.vfs_file_id</code>.
     */
    public Integer getVfsFileId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.collateral_agreement.agreement_state_id</code>.
     */
    public void setAgreementStateId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.collateral_agreement.agreement_state_id</code>.
     */
    public Integer getAgreementStateId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.collateral_agreement.billing_file_id</code>.
     */
    public void setBillingFileId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.collateral_agreement.billing_file_id</code>.
     */
    public Integer getBillingFileId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, String, String, LocalDateTime, Integer, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, String, String, LocalDateTime, Integer, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CollateralAgreement.COLLATERAL_AGREEMENT.COLLATERAL_AGREEMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CollateralAgreement.COLLATERAL_AGREEMENT.AGREEMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CollateralAgreement.COLLATERAL_AGREEMENT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CollateralAgreement.COLLATERAL_AGREEMENT.COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return CollateralAgreement.COLLATERAL_AGREEMENT.CREATION_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return CollateralAgreement.COLLATERAL_AGREEMENT.VFS_FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return CollateralAgreement.COLLATERAL_AGREEMENT.AGREEMENT_STATE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return CollateralAgreement.COLLATERAL_AGREEMENT.BILLING_FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCollateralAgreementId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAgreementId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getCreationTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getVfsFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getAgreementStateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getBillingFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CollateralAgreementRecord value1(Integer value) {
        setCollateralAgreementId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CollateralAgreementRecord value2(Integer value) {
        setAgreementId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CollateralAgreementRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CollateralAgreementRecord value4(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CollateralAgreementRecord value5(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CollateralAgreementRecord value6(Integer value) {
        setVfsFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CollateralAgreementRecord value7(Integer value) {
        setAgreementStateId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CollateralAgreementRecord value8(Integer value) {
        setBillingFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CollateralAgreementRecord values(Integer value1, Integer value2, String value3, String value4, LocalDateTime value5, Integer value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CollateralAgreementRecord
     */
    public CollateralAgreementRecord() {
        super(CollateralAgreement.COLLATERAL_AGREEMENT);
    }

    /**
     * Create a detached, initialised CollateralAgreementRecord
     */
    public CollateralAgreementRecord(Integer collateralAgreementId, Integer agreementId, String name, String comment, LocalDateTime creationTime, Integer vfsFileId, Integer agreementStateId, Integer billingFileId) {
        super(CollateralAgreement.COLLATERAL_AGREEMENT);

        set(0, collateralAgreementId);
        set(1, agreementId);
        set(2, name);
        set(3, comment);
        set(4, creationTime);
        set(5, vfsFileId);
        set(6, agreementStateId);
        set(7, billingFileId);
    }
}
