/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hh.jooq.tables.Device;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceRecord extends UpdatableRecordImpl<DeviceRecord> implements Record12<Integer, Long, String, String, Boolean, LocalDateTime, LocalDateTime, Integer, String, String, String, String> {

    private static final long serialVersionUID = -80769415;

    /**
     * Setter for <code>public.device.device_id</code>.
     */
    public void setDeviceId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.device.device_id</code>.
     */
    public Integer getDeviceId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.device.subscription_id</code>.
     */
    public void setSubscriptionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.device.subscription_id</code>.
     */
    public Long getSubscriptionId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.device.device_token</code>.
     */
    public void setDeviceToken(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.device.device_token</code>.
     */
    public String getDeviceToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.device.os_type</code>.
     */
    public void setOsType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.device.os_type</code>.
     */
    public String getOsType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.device.active</code>.
     */
    public void setActive(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.device.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.device.last_visit_time</code>.
     */
    public void setLastVisitTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.device.last_visit_time</code>.
     */
    public LocalDateTime getLastVisitTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.device.registration_time</code>.
     */
    public void setRegistrationTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.device.registration_time</code>.
     */
    public LocalDateTime getRegistrationTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.device.errors_qty</code>.
     */
    public void setErrorsQty(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.device.errors_qty</code>.
     */
    public Integer getErrorsQty() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.device.disactivation_cause</code>.
     */
    public void setDisactivationCause(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.device.disactivation_cause</code>.
     */
    public String getDisactivationCause() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.device.device_mode</code>.
     */
    public void setDeviceMode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.device.device_mode</code>.
     */
    public String getDeviceMode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.device.client_id</code>.
     */
    public void setClientId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.device.client_id</code>.
     */
    public String getClientId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.device.uuid</code>.
     */
    public void setUuid(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.device.uuid</code>.
     */
    public String getUuid() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Long, String, String, Boolean, LocalDateTime, LocalDateTime, Integer, String, String, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Long, String, String, Boolean, LocalDateTime, LocalDateTime, Integer, String, String, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Device.DEVICE.DEVICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Device.DEVICE.SUBSCRIPTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Device.DEVICE.DEVICE_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Device.DEVICE.OS_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Device.DEVICE.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return Device.DEVICE.LAST_VISIT_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return Device.DEVICE.REGISTRATION_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Device.DEVICE.ERRORS_QTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Device.DEVICE.DISACTIVATION_CAUSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Device.DEVICE.DEVICE_MODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Device.DEVICE.CLIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Device.DEVICE.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getDeviceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getSubscriptionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDeviceToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOsType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getLastVisitTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getRegistrationTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getErrorsQty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDisactivationCause();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getDeviceMode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value1(Integer value) {
        setDeviceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value2(Long value) {
        setSubscriptionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value3(String value) {
        setDeviceToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value4(String value) {
        setOsType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value5(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value6(LocalDateTime value) {
        setLastVisitTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value7(LocalDateTime value) {
        setRegistrationTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value8(Integer value) {
        setErrorsQty(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value9(String value) {
        setDisactivationCause(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value10(String value) {
        setDeviceMode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value11(String value) {
        setClientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value12(String value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord values(Integer value1, Long value2, String value3, String value4, Boolean value5, LocalDateTime value6, LocalDateTime value7, Integer value8, String value9, String value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeviceRecord
     */
    public DeviceRecord() {
        super(Device.DEVICE);
    }

    /**
     * Create a detached, initialised DeviceRecord
     */
    public DeviceRecord(Integer deviceId, Long subscriptionId, String deviceToken, String osType, Boolean active, LocalDateTime lastVisitTime, LocalDateTime registrationTime, Integer errorsQty, String disactivationCause, String deviceMode, String clientId, String uuid) {
        super(Device.DEVICE);

        set(0, deviceId);
        set(1, subscriptionId);
        set(2, deviceToken);
        set(3, osType);
        set(4, active);
        set(5, lastVisitTime);
        set(6, registrationTime);
        set(7, errorsQty);
        set(8, disactivationCause);
        set(9, deviceMode);
        set(10, clientId);
        set(11, uuid);
    }
}
