/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hh.jooq.tables.EmployerBlackList;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployerBlackListRecord extends UpdatableRecordImpl<EmployerBlackListRecord> implements Record4<Integer, LocalDateTime, Integer, Integer> {

    private static final long serialVersionUID = -1411065382;

    /**
     * Setter for <code>public.employer_black_list.employer_black_list_id</code>.
     */
    public void setEmployerBlackListId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.employer_black_list.employer_black_list_id</code>.
     */
    public Integer getEmployerBlackListId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.employer_black_list.creation_date</code>.
     */
    public void setCreationDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.employer_black_list.creation_date</code>.
     */
    public LocalDateTime getCreationDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.employer_black_list.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.employer_black_list.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.employer_black_list.employer_id</code>.
     */
    public void setEmployerId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.employer_black_list.employer_id</code>.
     */
    public Integer getEmployerId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, LocalDateTime, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, LocalDateTime, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EmployerBlackList.EMPLOYER_BLACK_LIST.EMPLOYER_BLACK_LIST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return EmployerBlackList.EMPLOYER_BLACK_LIST.CREATION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return EmployerBlackList.EMPLOYER_BLACK_LIST.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return EmployerBlackList.EMPLOYER_BLACK_LIST.EMPLOYER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEmployerBlackListId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getEmployerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployerBlackListRecord value1(Integer value) {
        setEmployerBlackListId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployerBlackListRecord value2(LocalDateTime value) {
        setCreationDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployerBlackListRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployerBlackListRecord value4(Integer value) {
        setEmployerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployerBlackListRecord values(Integer value1, LocalDateTime value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployerBlackListRecord
     */
    public EmployerBlackListRecord() {
        super(EmployerBlackList.EMPLOYER_BLACK_LIST);
    }

    /**
     * Create a detached, initialised EmployerBlackListRecord
     */
    public EmployerBlackListRecord(Integer employerBlackListId, LocalDateTime creationDate, Integer userId, Integer employerId) {
        super(EmployerBlackList.EMPLOYER_BLACK_LIST);

        set(0, employerBlackListId);
        set(1, creationDate);
        set(2, userId);
        set(3, employerId);
    }
}
