/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hh.jooq.tables.EventMailingEmployerLetter;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventMailingEmployerLetterRecord extends UpdatableRecordImpl<EventMailingEmployerLetterRecord> implements Record5<Long, Integer, LocalDateTime, LocalDateTime, Short> {

    private static final long serialVersionUID = 966372970;

    /**
     * Setter for <code>public.event_mailing_employer_letter.employer_letter_id</code>.
     */
    public void setEmployerLetterId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.event_mailing_employer_letter.employer_letter_id</code>.
     */
    public Long getEmployerLetterId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.event_mailing_employer_letter.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.event_mailing_employer_letter.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.event_mailing_employer_letter.creation_datetime</code>.
     */
    public void setCreationDatetime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.event_mailing_employer_letter.creation_datetime</code>.
     */
    public LocalDateTime getCreationDatetime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.event_mailing_employer_letter.last_changed_datetime</code>.
     */
    public void setLastChangedDatetime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.event_mailing_employer_letter.last_changed_datetime</code>.
     */
    public LocalDateTime getLastChangedDatetime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.event_mailing_employer_letter.status</code>.
     */
    public void setStatus(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.event_mailing_employer_letter.status</code>.
     */
    public Short getStatus() {
        return (Short) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Integer, LocalDateTime, LocalDateTime, Short> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Integer, LocalDateTime, LocalDateTime, Short> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return EventMailingEmployerLetter.EVENT_MAILING_EMPLOYER_LETTER.EMPLOYER_LETTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return EventMailingEmployerLetter.EVENT_MAILING_EMPLOYER_LETTER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field3() {
        return EventMailingEmployerLetter.EVENT_MAILING_EMPLOYER_LETTER.CREATION_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return EventMailingEmployerLetter.EVENT_MAILING_EMPLOYER_LETTER.LAST_CHANGED_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field5() {
        return EventMailingEmployerLetter.EVENT_MAILING_EMPLOYER_LETTER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getEmployerLetterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value3() {
        return getCreationDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getLastChangedDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventMailingEmployerLetterRecord value1(Long value) {
        setEmployerLetterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventMailingEmployerLetterRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventMailingEmployerLetterRecord value3(LocalDateTime value) {
        setCreationDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventMailingEmployerLetterRecord value4(LocalDateTime value) {
        setLastChangedDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventMailingEmployerLetterRecord value5(Short value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventMailingEmployerLetterRecord values(Long value1, Integer value2, LocalDateTime value3, LocalDateTime value4, Short value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventMailingEmployerLetterRecord
     */
    public EventMailingEmployerLetterRecord() {
        super(EventMailingEmployerLetter.EVENT_MAILING_EMPLOYER_LETTER);
    }

    /**
     * Create a detached, initialised EventMailingEmployerLetterRecord
     */
    public EventMailingEmployerLetterRecord(Long employerLetterId, Integer userId, LocalDateTime creationDatetime, LocalDateTime lastChangedDatetime, Short status) {
        super(EventMailingEmployerLetter.EVENT_MAILING_EMPLOYER_LETTER);

        set(0, employerLetterId);
        set(1, userId);
        set(2, creationDatetime);
        set(3, lastChangedDatetime);
        set(4, status);
    }
}
