/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hh.jooq.tables.EventEmployerManager;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventEmployerManagerRecord extends UpdatableRecordImpl<EventEmployerManagerRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 623229285;

    /**
     * Setter for <code>public.event_employer_manager.event_employer_manager_id</code>.
     */
    public void setEventEmployerManagerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.event_employer_manager.event_employer_manager_id</code>.
     */
    public Integer getEventEmployerManagerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.event_employer_manager.event_id</code>.
     */
    public void setEventId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.event_employer_manager.event_id</code>.
     */
    public Integer getEventId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.event_employer_manager.employer_manager_id</code>.
     */
    public void setEmployerManagerId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.event_employer_manager.employer_manager_id</code>.
     */
    public Integer getEmployerManagerId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EventEmployerManager.EVENT_EMPLOYER_MANAGER.EVENT_EMPLOYER_MANAGER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return EventEmployerManager.EVENT_EMPLOYER_MANAGER.EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return EventEmployerManager.EVENT_EMPLOYER_MANAGER.EMPLOYER_MANAGER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEventEmployerManagerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getEmployerManagerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventEmployerManagerRecord value1(Integer value) {
        setEventEmployerManagerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventEmployerManagerRecord value2(Integer value) {
        setEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventEmployerManagerRecord value3(Integer value) {
        setEmployerManagerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventEmployerManagerRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventEmployerManagerRecord
     */
    public EventEmployerManagerRecord() {
        super(EventEmployerManager.EVENT_EMPLOYER_MANAGER);
    }

    /**
     * Create a detached, initialised EventEmployerManagerRecord
     */
    public EventEmployerManagerRecord(Integer eventEmployerManagerId, Integer eventId, Integer employerManagerId) {
        super(EventEmployerManager.EVENT_EMPLOYER_MANAGER);

        set(0, eventEmployerManagerId);
        set(1, eventId);
        set(2, employerManagerId);
    }
}
