/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hh.jooq.tables.Experience;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperienceRecord extends UpdatableRecordImpl<ExperienceRecord> implements Record14<Integer, Integer, LocalDateTime, LocalDateTime, String, String, String, Integer, String, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -977341956;

    /**
     * Setter for <code>public.experience.experience_id</code>.
     */
    public void setExperienceId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.experience.experience_id</code>.
     */
    public Integer getExperienceId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.experience.resume_id</code>.
     */
    public void setResumeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.experience.resume_id</code>.
     */
    public Integer getResumeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.experience.start_date</code>.
     */
    public void setStartDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.experience.start_date</code>.
     */
    public LocalDateTime getStartDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.experience.end_date</code>.
     */
    public void setEndDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.experience.end_date</code>.
     */
    public LocalDateTime getEndDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.experience.organization</code>.
     */
    public void setOrganization(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.experience.organization</code>.
     */
    public String getOrganization() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.experience.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.experience.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.experience.post</code>.
     */
    public void setPost(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.experience.post</code>.
     */
    public String getPost() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.experience.industry_id</code>.
     */
    public void setIndustryId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.experience.industry_id</code>.
     */
    public Integer getIndustryId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.experience.company_url</code>.
     */
    public void setCompanyUrl(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.experience.company_url</code>.
     */
    public String getCompanyUrl() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.experience.company_area_id</code>.
     */
    public void setCompanyAreaId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.experience.company_area_id</code>.
     */
    public Integer getCompanyAreaId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.experience.company_synonym_id</code>.
     */
    public void setCompanySynonymId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.experience.company_synonym_id</code>.
     */
    public Integer getCompanySynonymId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.experience.company_id</code>.
     */
    public void setCompanyId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.experience.company_id</code>.
     */
    public Integer getCompanyId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.experience.mapped_company_id</code>.
     */
    public void setMappedCompanyId(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.experience.mapped_company_id</code>.
     */
    public Integer getMappedCompanyId() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.experience.mapping_status</code>.
     */
    public void setMappingStatus(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.experience.mapping_status</code>.
     */
    public Integer getMappingStatus() {
        return (Integer) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, Integer, LocalDateTime, LocalDateTime, String, String, String, Integer, String, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, Integer, LocalDateTime, LocalDateTime, String, String, String, Integer, String, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Experience.EXPERIENCE.EXPERIENCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Experience.EXPERIENCE.RESUME_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field3() {
        return Experience.EXPERIENCE.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return Experience.EXPERIENCE.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Experience.EXPERIENCE.ORGANIZATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Experience.EXPERIENCE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Experience.EXPERIENCE.POST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Experience.EXPERIENCE.INDUSTRY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Experience.EXPERIENCE.COMPANY_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Experience.EXPERIENCE.COMPANY_AREA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Experience.EXPERIENCE.COMPANY_SYNONYM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return Experience.EXPERIENCE.COMPANY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Experience.EXPERIENCE.MAPPED_COMPANY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return Experience.EXPERIENCE.MAPPING_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getExperienceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getResumeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value3() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getIndustryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCompanyUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getCompanyAreaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getCompanySynonymId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getMappedCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getMappingStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value1(Integer value) {
        setExperienceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value2(Integer value) {
        setResumeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value3(LocalDateTime value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value4(LocalDateTime value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value5(String value) {
        setOrganization(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value6(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value7(String value) {
        setPost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value8(Integer value) {
        setIndustryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value9(String value) {
        setCompanyUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value10(Integer value) {
        setCompanyAreaId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value11(Integer value) {
        setCompanySynonymId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value12(Integer value) {
        setCompanyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value13(Integer value) {
        setMappedCompanyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value14(Integer value) {
        setMappingStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord values(Integer value1, Integer value2, LocalDateTime value3, LocalDateTime value4, String value5, String value6, String value7, Integer value8, String value9, Integer value10, Integer value11, Integer value12, Integer value13, Integer value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExperienceRecord
     */
    public ExperienceRecord() {
        super(Experience.EXPERIENCE);
    }

    /**
     * Create a detached, initialised ExperienceRecord
     */
    public ExperienceRecord(Integer experienceId, Integer resumeId, LocalDateTime startDate, LocalDateTime endDate, String organization, String description, String post, Integer industryId, String companyUrl, Integer companyAreaId, Integer companySynonymId, Integer companyId, Integer mappedCompanyId, Integer mappingStatus) {
        super(Experience.EXPERIENCE);

        set(0, experienceId);
        set(1, resumeId);
        set(2, startDate);
        set(3, endDate);
        set(4, organization);
        set(5, description);
        set(6, post);
        set(7, industryId);
        set(8, companyUrl);
        set(9, companyAreaId);
        set(10, companySynonymId);
        set(11, companyId);
        set(12, mappedCompanyId);
        set(13, mappingStatus);
    }
}
