/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hh.jooq.tables.MailingBlock;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MailingBlockRecord extends UpdatableRecordImpl<MailingBlockRecord> implements Record7<Integer, String, Integer, Integer, Integer, String, String> {

    private static final long serialVersionUID = -529973606;

    /**
     * Setter for <code>public.mailing_block.mailing_block_id</code>.
     */
    public void setMailingBlockId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mailing_block.mailing_block_id</code>.
     */
    public Integer getMailingBlockId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.mailing_block.block_value</code>.
     */
    public void setBlockValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mailing_block.block_value</code>.
     */
    public String getBlockValue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.mailing_block.mailing_id</code>.
     */
    public void setMailingId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mailing_block.mailing_id</code>.
     */
    public Integer getMailingId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.mailing_block.block_index</code>.
     */
    public void setBlockIndex(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mailing_block.block_index</code>.
     */
    public Integer getBlockIndex() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.mailing_block.mailing_user_group_id</code>.
     */
    public void setMailingUserGroupId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mailing_block.mailing_user_group_id</code>.
     */
    public Integer getMailingUserGroupId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.mailing_block.subject</code>.
     */
    public void setSubject(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mailing_block.subject</code>.
     */
    public String getSubject() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mailing_block.title</code>.
     */
    public void setTitle(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mailing_block.title</code>.
     */
    public String getTitle() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Integer, Integer, Integer, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Integer, Integer, Integer, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MailingBlock.MAILING_BLOCK.MAILING_BLOCK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MailingBlock.MAILING_BLOCK.BLOCK_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MailingBlock.MAILING_BLOCK.MAILING_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return MailingBlock.MAILING_BLOCK.BLOCK_INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return MailingBlock.MAILING_BLOCK.MAILING_USER_GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MailingBlock.MAILING_BLOCK.SUBJECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MailingBlock.MAILING_BLOCK.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMailingBlockId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBlockValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMailingId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getBlockIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getMailingUserGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSubject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MailingBlockRecord value1(Integer value) {
        setMailingBlockId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MailingBlockRecord value2(String value) {
        setBlockValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MailingBlockRecord value3(Integer value) {
        setMailingId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MailingBlockRecord value4(Integer value) {
        setBlockIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MailingBlockRecord value5(Integer value) {
        setMailingUserGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MailingBlockRecord value6(String value) {
        setSubject(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MailingBlockRecord value7(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MailingBlockRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MailingBlockRecord
     */
    public MailingBlockRecord() {
        super(MailingBlock.MAILING_BLOCK);
    }

    /**
     * Create a detached, initialised MailingBlockRecord
     */
    public MailingBlockRecord(Integer mailingBlockId, String blockValue, Integer mailingId, Integer blockIndex, Integer mailingUserGroupId, String subject, String title) {
        super(MailingBlock.MAILING_BLOCK);

        set(0, mailingBlockId);
        set(1, blockValue);
        set(2, mailingId);
        set(3, blockIndex);
        set(4, mailingUserGroupId);
        set(5, subject);
        set(6, title);
    }
}
