/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hh.jooq.tables.MaxBillUid;


/**
 * Caching acctual max bill uid values for different bill types within accounts
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MaxBillUidRecord extends UpdatableRecordImpl<MaxBillUidRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 182849151;

    /**
     * Setter for <code>public.max_bill_uid.bill_type</code>.
     */
    public void setBillType(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.max_bill_uid.bill_type</code>.
     */
    public Integer getBillType() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.max_bill_uid.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.max_bill_uid.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.max_bill_uid.max_value</code>.
     */
    public void setMaxValue(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.max_bill_uid.max_value</code>.
     */
    public Integer getMaxValue() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.max_bill_uid.version_</code>.
     */
    public void setVersion_(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.max_bill_uid.version_</code>.
     */
    public Integer getVersion_() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MaxBillUid.MAX_BILL_UID.BILL_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MaxBillUid.MAX_BILL_UID.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MaxBillUid.MAX_BILL_UID.MAX_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return MaxBillUid.MAX_BILL_UID.VERSION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBillType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMaxValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getVersion_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaxBillUidRecord value1(Integer value) {
        setBillType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaxBillUidRecord value2(Integer value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaxBillUidRecord value3(Integer value) {
        setMaxValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaxBillUidRecord value4(Integer value) {
        setVersion_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaxBillUidRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MaxBillUidRecord
     */
    public MaxBillUidRecord() {
        super(MaxBillUid.MAX_BILL_UID);
    }

    /**
     * Create a detached, initialised MaxBillUidRecord
     */
    public MaxBillUidRecord(Integer billType, Integer accountId, Integer maxValue, Integer version_) {
        super(MaxBillUid.MAX_BILL_UID);

        set(0, billType);
        set(1, accountId);
        set(2, maxValue);
        set(3, version_);
    }
}
