/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;

import ru.hh.jooq.tables.ParentId;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParentIdRecord extends TableRecordImpl<ParentIdRecord> implements Record1<Integer> {

    private static final long serialVersionUID = 1608576513;

    /**
     * Setter for <code>public.parent_id.area_id</code>.
     */
    public void setAreaId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.parent_id.area_id</code>.
     */
    public Integer getAreaId() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Integer> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ParentId.PARENT_ID.AREA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getAreaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParentIdRecord value1(Integer value) {
        setAreaId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParentIdRecord values(Integer value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ParentIdRecord
     */
    public ParentIdRecord() {
        super(ParentId.PARENT_ID);
    }

    /**
     * Create a detached, initialised ParentIdRecord
     */
    public ParentIdRecord(Integer areaId) {
        super(ParentId.PARENT_ID);

        set(0, areaId);
    }
}
