/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hh.jooq.tables.PollOptions;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PollOptionsRecord extends UpdatableRecordImpl<PollOptionsRecord> implements Record4<Integer, Integer, String, Integer> {

    private static final long serialVersionUID = -1915457475;

    /**
     * Setter for <code>public.poll_options.poll_option_id</code>.
     */
    public void setPollOptionId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.poll_options.poll_option_id</code>.
     */
    public Integer getPollOptionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.poll_options.question_id</code>.
     */
    public void setQuestionId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.poll_options.question_id</code>.
     */
    public Integer getQuestionId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.poll_options.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.poll_options.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.poll_options.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.poll_options.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PollOptions.POLL_OPTIONS.POLL_OPTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PollOptions.POLL_OPTIONS.QUESTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PollOptions.POLL_OPTIONS.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PollOptions.POLL_OPTIONS.SORT_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPollOptionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getQuestionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSortOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PollOptionsRecord value1(Integer value) {
        setPollOptionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PollOptionsRecord value2(Integer value) {
        setQuestionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PollOptionsRecord value3(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PollOptionsRecord value4(Integer value) {
        setSortOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PollOptionsRecord values(Integer value1, Integer value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PollOptionsRecord
     */
    public PollOptionsRecord() {
        super(PollOptions.POLL_OPTIONS);
    }

    /**
     * Create a detached, initialised PollOptionsRecord
     */
    public PollOptionsRecord(Integer pollOptionId, Integer questionId, String value, Integer sortOrder) {
        super(PollOptions.POLL_OPTIONS);

        set(0, pollOptionId);
        set(1, questionId);
        set(2, value);
        set(3, sortOrder);
    }
}
