/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hh.jooq.tables.Product;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record17<Integer, String, Boolean, String, Integer, Integer, Boolean, Boolean, Boolean, Boolean, Integer, Integer, Integer, Integer, Boolean, String, Integer> {

    private static final long serialVersionUID = -1819208646;

    /**
     * Setter for <code>public.product.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.product.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.product.deed_name</code>.
     */
    public void setDeedName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.product.deed_name</code>.
     */
    public String getDeedName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.product.temporal</code>.
     */
    public void setTemporal(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.product.temporal</code>.
     */
    public Boolean getTemporal() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.product.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.product.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.product.period_length</code>.
     */
    public void setPeriodLength(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.product.period_length</code>.
     */
    public Integer getPeriodLength() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.product.bdzp_region_id</code>.
     */
    public void setBdzpRegionId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.product.bdzp_region_id</code>.
     */
    public Integer getBdzpRegionId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.product.bdzp_participant</code>. not used, can be dropped
     */
    public void setBdzpParticipant(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.product.bdzp_participant</code>. not used, can be dropped
     */
    public Boolean getBdzpParticipant() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.product.generated</code>.
     */
    public void setGenerated(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.product.generated</code>.
     */
    public Boolean getGenerated() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.product.allow_mobile</code>.
     */
    public void setAllowMobile(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.product.allow_mobile</code>.
     */
    public Boolean getAllowMobile() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.product.allow_desktop</code>.
     */
    public void setAllowDesktop(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.product.allow_desktop</code>.
     */
    public Boolean getAllowDesktop() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.product.z6_page_type</code>.
     */
    public void setZ6PageType(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.product.z6_page_type</code>.
     */
    public Integer getZ6PageType() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.product.z6_region_id</code>.
     */
    public void setZ6RegionId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.product.z6_region_id</code>.
     */
    public Integer getZ6RegionId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.product.z5_type</code>.
     */
    public void setZ5Type(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.product.z5_type</code>.
     */
    public Integer getZ5Type() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.product.z5_template_count</code>.
     */
    public void setZ5TemplateCount(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.product.z5_template_count</code>.
     */
    public Integer getZ5TemplateCount() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.product.custom_flag_1</code>. HH-56218 Used for custom product data (for JC it is agency flag)
     */
    public void setCustomFlag_1(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.product.custom_flag_1</code>. HH-56218 Used for custom product data (for JC it is agency flag)
     */
    public Boolean getCustomFlag_1() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>public.product.code_1c</code>. HH-56822 Used for 1C code providing
     */
    public void setCode_1c(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.product.code_1c</code>. HH-56822 Used for 1C code providing
     */
    public String getCode_1c() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.product.custom_int_field_1</code>. HH-58409 add common int field for products hierarchy
     */
    public void setCustomIntField_1(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.product.custom_int_field_1</code>. HH-58409 add common int field for products hierarchy
     */
    public Integer getCustomIntField_1() {
        return (Integer) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, String, Boolean, String, Integer, Integer, Boolean, Boolean, Boolean, Boolean, Integer, Integer, Integer, Integer, Boolean, String, Integer> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, String, Boolean, String, Integer, Integer, Boolean, Boolean, Boolean, Boolean, Integer, Integer, Integer, Integer, Boolean, String, Integer> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Product.PRODUCT.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Product.PRODUCT.DEED_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return Product.PRODUCT.TEMPORAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Product.PRODUCT.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Product.PRODUCT.PERIOD_LENGTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Product.PRODUCT.BDZP_REGION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return Product.PRODUCT.BDZP_PARTICIPANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Product.PRODUCT.GENERATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return Product.PRODUCT.ALLOW_MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return Product.PRODUCT.ALLOW_DESKTOP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Product.PRODUCT.Z6_PAGE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return Product.PRODUCT.Z6_REGION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Product.PRODUCT.Z5_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return Product.PRODUCT.Z5_TEMPLATE_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field15() {
        return Product.PRODUCT.CUSTOM_FLAG_1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Product.PRODUCT.CODE_1C;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field17() {
        return Product.PRODUCT.CUSTOM_INT_FIELD_1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDeedName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getTemporal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getPeriodLength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getBdzpRegionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getBdzpParticipant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getGenerated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getAllowMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getAllowDesktop();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getZ6PageType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getZ6RegionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getZ5Type();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getZ5TemplateCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value15() {
        return getCustomFlag_1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getCode_1c();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value17() {
        return getCustomIntField_1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value1(Integer value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value2(String value) {
        setDeedName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value3(Boolean value) {
        setTemporal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value4(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value5(Integer value) {
        setPeriodLength(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value6(Integer value) {
        setBdzpRegionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value7(Boolean value) {
        setBdzpParticipant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value8(Boolean value) {
        setGenerated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value9(Boolean value) {
        setAllowMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value10(Boolean value) {
        setAllowDesktop(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value11(Integer value) {
        setZ6PageType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value12(Integer value) {
        setZ6RegionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value13(Integer value) {
        setZ5Type(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value14(Integer value) {
        setZ5TemplateCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value15(Boolean value) {
        setCustomFlag_1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value16(String value) {
        setCode_1c(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value17(Integer value) {
        setCustomIntField_1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord values(Integer value1, String value2, Boolean value3, String value4, Integer value5, Integer value6, Boolean value7, Boolean value8, Boolean value9, Boolean value10, Integer value11, Integer value12, Integer value13, Integer value14, Boolean value15, String value16, Integer value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(Integer productId, String deedName, Boolean temporal, String code, Integer periodLength, Integer bdzpRegionId, Boolean bdzpParticipant, Boolean generated, Boolean allowMobile, Boolean allowDesktop, Integer z6PageType, Integer z6RegionId, Integer z5Type, Integer z5TemplateCount, Boolean customFlag_1, String code_1c, Integer customIntField_1) {
        super(Product.PRODUCT);

        set(0, productId);
        set(1, deedName);
        set(2, temporal);
        set(3, code);
        set(4, periodLength);
        set(5, bdzpRegionId);
        set(6, bdzpParticipant);
        set(7, generated);
        set(8, allowMobile);
        set(9, allowDesktop);
        set(10, z6PageType);
        set(11, z6RegionId);
        set(12, z5Type);
        set(13, z5TemplateCount);
        set(14, customFlag_1);
        set(15, code_1c);
        set(16, customIntField_1);
    }
}
