/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import ru.hh.jooq.tables.ResumeSpecialization;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResumeSpecializationRecord extends TableRecordImpl<ResumeSpecializationRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 2026796797;

    /**
     * Setter for <code>public.resume_specialization.resume_id</code>.
     */
    public void setResumeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.resume_specialization.resume_id</code>.
     */
    public Integer getResumeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.resume_specialization.specialization_id</code>.
     */
    public void setSpecializationId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.resume_specialization.specialization_id</code>.
     */
    public Integer getSpecializationId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ResumeSpecialization.RESUME_SPECIALIZATION.RESUME_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ResumeSpecialization.RESUME_SPECIALIZATION.SPECIALIZATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getResumeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSpecializationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResumeSpecializationRecord value1(Integer value) {
        setResumeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResumeSpecializationRecord value2(Integer value) {
        setSpecializationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResumeSpecializationRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResumeSpecializationRecord
     */
    public ResumeSpecializationRecord() {
        super(ResumeSpecialization.RESUME_SPECIALIZATION);
    }

    /**
     * Create a detached, initialised ResumeSpecializationRecord
     */
    public ResumeSpecializationRecord(Integer resumeId, Integer specializationId) {
        super(ResumeSpecialization.RESUME_SPECIALIZATION);

        set(0, resumeId);
        set(1, specializationId);
    }
}
