/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import ru.hh.jooq.tables.ResumeDenyEmployer;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResumeDenyEmployerRecord extends TableRecordImpl<ResumeDenyEmployerRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 145801805;

    /**
     * Setter for <code>public.resume_deny_employer.employer_id</code>.
     */
    public void setEmployerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.resume_deny_employer.employer_id</code>.
     */
    public Integer getEmployerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.resume_deny_employer.resume_id</code>.
     */
    public void setResumeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.resume_deny_employer.resume_id</code>.
     */
    public Integer getResumeId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ResumeDenyEmployer.RESUME_DENY_EMPLOYER.EMPLOYER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ResumeDenyEmployer.RESUME_DENY_EMPLOYER.RESUME_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEmployerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getResumeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResumeDenyEmployerRecord value1(Integer value) {
        setEmployerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResumeDenyEmployerRecord value2(Integer value) {
        setResumeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResumeDenyEmployerRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResumeDenyEmployerRecord
     */
    public ResumeDenyEmployerRecord() {
        super(ResumeDenyEmployer.RESUME_DENY_EMPLOYER);
    }

    /**
     * Create a detached, initialised ResumeDenyEmployerRecord
     */
    public ResumeDenyEmployerRecord(Integer employerId, Integer resumeId) {
        super(ResumeDenyEmployer.RESUME_DENY_EMPLOYER);

        set(0, employerId);
        set(1, resumeId);
    }
}
