/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hh.jooq.tables.ServiceItemPrice;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServiceItemPriceRecord extends UpdatableRecordImpl<ServiceItemPriceRecord> implements Record6<Integer, Long, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = -1430775218;

    /**
     * Setter for <code>public.service_item_price.seller_account_id</code>.
     */
    public void setSellerAccountId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.service_item_price.seller_account_id</code>.
     */
    public Integer getSellerAccountId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.service_item_price.price</code>.
     */
    public void setPrice(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.service_item_price.price</code>.
     */
    public Long getPrice() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.service_item_price.service_entry</code>.
     */
    public void setServiceEntry(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.service_item_price.service_entry</code>.
     */
    public String getServiceEntry() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.service_item_price.rounding_mode</code>.
     */
    public void setRoundingMode(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.service_item_price.rounding_mode</code>.
     */
    public Integer getRoundingMode() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.service_item_price.rounding_scale</code>.
     */
    public void setRoundingScale(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.service_item_price.rounding_scale</code>.
     */
    public Integer getRoundingScale() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.service_item_price.bill_type</code>.
     */
    public void setBillType(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.service_item_price.bill_type</code>.
     */
    public Integer getBillType() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Long, String, Integer, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Long, String, Integer, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ServiceItemPrice.SERVICE_ITEM_PRICE.SELLER_ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ServiceItemPrice.SERVICE_ITEM_PRICE.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ServiceItemPrice.SERVICE_ITEM_PRICE.SERVICE_ENTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ServiceItemPrice.SERVICE_ITEM_PRICE.ROUNDING_MODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ServiceItemPrice.SERVICE_ITEM_PRICE.ROUNDING_SCALE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ServiceItemPrice.SERVICE_ITEM_PRICE.BILL_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSellerAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getServiceEntry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getRoundingMode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getRoundingScale();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getBillType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceItemPriceRecord value1(Integer value) {
        setSellerAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceItemPriceRecord value2(Long value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceItemPriceRecord value3(String value) {
        setServiceEntry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceItemPriceRecord value4(Integer value) {
        setRoundingMode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceItemPriceRecord value5(Integer value) {
        setRoundingScale(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceItemPriceRecord value6(Integer value) {
        setBillType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceItemPriceRecord values(Integer value1, Long value2, String value3, Integer value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServiceItemPriceRecord
     */
    public ServiceItemPriceRecord() {
        super(ServiceItemPrice.SERVICE_ITEM_PRICE);
    }

    /**
     * Create a detached, initialised ServiceItemPriceRecord
     */
    public ServiceItemPriceRecord(Integer sellerAccountId, Long price, String serviceEntry, Integer roundingMode, Integer roundingScale, Integer billType) {
        super(ServiceItemPrice.SERVICE_ITEM_PRICE);

        set(0, sellerAccountId);
        set(1, price);
        set(2, serviceEntry);
        set(3, roundingMode);
        set(4, roundingScale);
        set(5, billType);
    }
}
