/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hh.jooq.tables.ServiceItemPriceRate;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServiceItemPriceRateRecord extends UpdatableRecordImpl<ServiceItemPriceRateRecord> implements Record5<Integer, BigDecimal, String, Integer, Integer> {

    private static final long serialVersionUID = -2093610614;

    /**
     * Setter for <code>public.service_item_price_rate.items_count</code>.
     */
    public void setItemsCount(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.service_item_price_rate.items_count</code>.
     */
    public Integer getItemsCount() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.service_item_price_rate.rate</code>.
     */
    public void setRate(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.service_item_price_rate.rate</code>.
     */
    public BigDecimal getRate() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.service_item_price_rate.service_entry</code>.
     */
    public void setServiceEntry(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.service_item_price_rate.service_entry</code>.
     */
    public String getServiceEntry() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.service_item_price_rate.seller_account_id</code>.
     */
    public void setSellerAccountId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.service_item_price_rate.seller_account_id</code>.
     */
    public Integer getSellerAccountId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.service_item_price_rate.action_period</code>.
     */
    public void setActionPeriod(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.service_item_price_rate.action_period</code>.
     */
    public Integer getActionPeriod() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Integer, String, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, BigDecimal, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, BigDecimal, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ServiceItemPriceRate.SERVICE_ITEM_PRICE_RATE.ITEMS_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return ServiceItemPriceRate.SERVICE_ITEM_PRICE_RATE.RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ServiceItemPriceRate.SERVICE_ITEM_PRICE_RATE.SERVICE_ENTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ServiceItemPriceRate.SERVICE_ITEM_PRICE_RATE.SELLER_ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ServiceItemPriceRate.SERVICE_ITEM_PRICE_RATE.ACTION_PERIOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getItemsCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getServiceEntry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSellerAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getActionPeriod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceItemPriceRateRecord value1(Integer value) {
        setItemsCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceItemPriceRateRecord value2(BigDecimal value) {
        setRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceItemPriceRateRecord value3(String value) {
        setServiceEntry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceItemPriceRateRecord value4(Integer value) {
        setSellerAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceItemPriceRateRecord value5(Integer value) {
        setActionPeriod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceItemPriceRateRecord values(Integer value1, BigDecimal value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServiceItemPriceRateRecord
     */
    public ServiceItemPriceRateRecord() {
        super(ServiceItemPriceRate.SERVICE_ITEM_PRICE_RATE);
    }

    /**
     * Create a detached, initialised ServiceItemPriceRateRecord
     */
    public ServiceItemPriceRateRecord(Integer itemsCount, BigDecimal rate, String serviceEntry, Integer sellerAccountId, Integer actionPeriod) {
        super(ServiceItemPriceRate.SERVICE_ITEM_PRICE_RATE);

        set(0, itemsCount);
        set(1, rate);
        set(2, serviceEntry);
        set(3, sellerAccountId);
        set(4, actionPeriod);
    }
}
