/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hh.jooq.tables.UserTagsForMailing;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTagsForMailingRecord extends UpdatableRecordImpl<UserTagsForMailingRecord> implements Record3<Integer, String, LocalDateTime> {

    private static final long serialVersionUID = 431670161;

    /**
     * Setter for <code>public.user_tags_for_mailing.hhid</code>.
     */
    public void setHhid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_tags_for_mailing.hhid</code>.
     */
    public Integer getHhid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.user_tags_for_mailing.tag</code>.
     */
    public void setTag(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_tags_for_mailing.tag</code>.
     */
    public String getTag() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_tags_for_mailing.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_tags_for_mailing.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserTagsForMailing.USER_TAGS_FOR_MAILING.HHID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserTagsForMailing.USER_TAGS_FOR_MAILING.TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field3() {
        return UserTagsForMailing.USER_TAGS_FOR_MAILING.CREATION_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getHhid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value3() {
        return getCreationTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTagsForMailingRecord value1(Integer value) {
        setHhid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTagsForMailingRecord value2(String value) {
        setTag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTagsForMailingRecord value3(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTagsForMailingRecord values(Integer value1, String value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserTagsForMailingRecord
     */
    public UserTagsForMailingRecord() {
        super(UserTagsForMailing.USER_TAGS_FOR_MAILING);
    }

    /**
     * Create a detached, initialised UserTagsForMailingRecord
     */
    public UserTagsForMailingRecord(Integer hhid, String tag, LocalDateTime creationTime) {
        super(UserTagsForMailing.USER_TAGS_FOR_MAILING);

        set(0, hhid);
        set(1, tag);
        set(2, creationTime);
    }
}
