/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hh.jooq.tables.VerificationActs;


/**
 * Акты сверки из 1С
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VerificationActsRecord extends UpdatableRecordImpl<VerificationActsRecord> implements Record19<Integer, LocalDateTime, LocalDateTime, LocalDateTime, LocalDate, LocalDate, Boolean, Integer, Integer, Integer, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, String, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1336156614;

    /**
     * Setter for <code>public.verification_acts.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.verification_acts.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.verification_acts.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.verification_acts.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.verification_acts.download_time</code>.
     */
    public void setDownloadTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.verification_acts.download_time</code>.
     */
    public LocalDateTime getDownloadTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.verification_acts.completed</code>.
     */
    public void setCompleted(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.verification_acts.completed</code>.
     */
    public LocalDateTime getCompleted() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.verification_acts.date_from</code>.
     */
    public void setDateFrom(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.verification_acts.date_from</code>.
     */
    public LocalDate getDateFrom() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.verification_acts.date_to</code>.
     */
    public void setDateTo(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.verification_acts.date_to</code>.
     */
    public LocalDate getDateTo() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>public.verification_acts.handicraft</code>.
     */
    public void setHandicraft(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.verification_acts.handicraft</code>.
     */
    public Boolean getHandicraft() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.verification_acts.payer_id</code>.
     */
    public void setPayerId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.verification_acts.payer_id</code>.
     */
    public Integer getPayerId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.verification_acts.file_id</code>.
     */
    public void setFileId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.verification_acts.file_id</code>.
     */
    public Integer getFileId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.verification_acts.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.verification_acts.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.verification_acts.original_requested</code>.
     */
    public void setOriginalRequested(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.verification_acts.original_requested</code>.
     */
    public LocalDateTime getOriginalRequested() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>public.verification_acts.original_notified</code>.
     */
    public void setOriginalNotified(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.verification_acts.original_notified</code>.
     */
    public LocalDateTime getOriginalNotified() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.verification_acts.original_processed</code>.
     */
    public void setOriginalProcessed(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.verification_acts.original_processed</code>.
     */
    public LocalDateTime getOriginalProcessed() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>public.verification_acts.download_confirmed</code>.
     */
    public void setDownloadConfirmed(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.verification_acts.download_confirmed</code>.
     */
    public LocalDateTime getDownloadConfirmed() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.verification_acts.tax_number</code>.
     */
    public void setTaxNumber(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.verification_acts.tax_number</code>.
     */
    public String getTaxNumber() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.verification_acts.kpp</code>.
     */
    public void setKpp(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.verification_acts.kpp</code>.
     */
    public String getKpp() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.verification_acts.original_fail_code</code>.
     */
    public void setOriginalFailCode(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.verification_acts.original_fail_code</code>.
     */
    public Integer getOriginalFailCode() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>public.verification_acts.original_requester_id</code>.
     */
    public void setOriginalRequesterId(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.verification_acts.original_requester_id</code>.
     */
    public Integer getOriginalRequesterId() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.verification_acts.billing_file_id</code>.
     */
    public void setBillingFileId(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.verification_acts.billing_file_id</code>.
     */
    public Integer getBillingFileId() {
        return (Integer) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Integer, LocalDateTime, LocalDateTime, LocalDateTime, LocalDate, LocalDate, Boolean, Integer, Integer, Integer, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, String, String, Integer, Integer, Integer> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Integer, LocalDateTime, LocalDateTime, LocalDateTime, LocalDate, LocalDate, Boolean, Integer, Integer, Integer, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, String, String, Integer, Integer, Integer> valuesRow() {
        return (Row19) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VerificationActs.VERIFICATION_ACTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return VerificationActs.VERIFICATION_ACTS.CREATION_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field3() {
        return VerificationActs.VERIFICATION_ACTS.DOWNLOAD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return VerificationActs.VERIFICATION_ACTS.COMPLETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field5() {
        return VerificationActs.VERIFICATION_ACTS.DATE_FROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field6() {
        return VerificationActs.VERIFICATION_ACTS.DATE_TO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return VerificationActs.VERIFICATION_ACTS.HANDICRAFT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return VerificationActs.VERIFICATION_ACTS.PAYER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return VerificationActs.VERIFICATION_ACTS.FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return VerificationActs.VERIFICATION_ACTS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return VerificationActs.VERIFICATION_ACTS.ORIGINAL_REQUESTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field12() {
        return VerificationActs.VERIFICATION_ACTS.ORIGINAL_NOTIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field13() {
        return VerificationActs.VERIFICATION_ACTS.ORIGINAL_PROCESSED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field14() {
        return VerificationActs.VERIFICATION_ACTS.DOWNLOAD_CONFIRMED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return VerificationActs.VERIFICATION_ACTS.TAX_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return VerificationActs.VERIFICATION_ACTS.KPP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field17() {
        return VerificationActs.VERIFICATION_ACTS.ORIGINAL_FAIL_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field18() {
        return VerificationActs.VERIFICATION_ACTS.ORIGINAL_REQUESTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field19() {
        return VerificationActs.VERIFICATION_ACTS.BILLING_FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getCreationTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value3() {
        return getDownloadTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getCompleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value5() {
        return getDateFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value6() {
        return getDateTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getHandicraft();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getPayerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getOriginalRequested();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value12() {
        return getOriginalNotified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value13() {
        return getOriginalProcessed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value14() {
        return getDownloadConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getTaxNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getKpp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value17() {
        return getOriginalFailCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value18() {
        return getOriginalRequesterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value19() {
        return getBillingFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value2(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value3(LocalDateTime value) {
        setDownloadTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value4(LocalDateTime value) {
        setCompleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value5(LocalDate value) {
        setDateFrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value6(LocalDate value) {
        setDateTo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value7(Boolean value) {
        setHandicraft(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value8(Integer value) {
        setPayerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value9(Integer value) {
        setFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value10(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value11(LocalDateTime value) {
        setOriginalRequested(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value12(LocalDateTime value) {
        setOriginalNotified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value13(LocalDateTime value) {
        setOriginalProcessed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value14(LocalDateTime value) {
        setDownloadConfirmed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value15(String value) {
        setTaxNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value16(String value) {
        setKpp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value17(Integer value) {
        setOriginalFailCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value18(Integer value) {
        setOriginalRequesterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord value19(Integer value) {
        setBillingFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationActsRecord values(Integer value1, LocalDateTime value2, LocalDateTime value3, LocalDateTime value4, LocalDate value5, LocalDate value6, Boolean value7, Integer value8, Integer value9, Integer value10, LocalDateTime value11, LocalDateTime value12, LocalDateTime value13, LocalDateTime value14, String value15, String value16, Integer value17, Integer value18, Integer value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VerificationActsRecord
     */
    public VerificationActsRecord() {
        super(VerificationActs.VERIFICATION_ACTS);
    }

    /**
     * Create a detached, initialised VerificationActsRecord
     */
    public VerificationActsRecord(Integer id, LocalDateTime creationTime, LocalDateTime downloadTime, LocalDateTime completed, LocalDate dateFrom, LocalDate dateTo, Boolean handicraft, Integer payerId, Integer fileId, Integer userId, LocalDateTime originalRequested, LocalDateTime originalNotified, LocalDateTime originalProcessed, LocalDateTime downloadConfirmed, String taxNumber, String kpp, Integer originalFailCode, Integer originalRequesterId, Integer billingFileId) {
        super(VerificationActs.VERIFICATION_ACTS);

        set(0, id);
        set(1, creationTime);
        set(2, downloadTime);
        set(3, completed);
        set(4, dateFrom);
        set(5, dateTo);
        set(6, handicraft);
        set(7, payerId);
        set(8, fileId);
        set(9, userId);
        set(10, originalRequested);
        set(11, originalNotified);
        set(12, originalProcessed);
        set(13, downloadConfirmed);
        set(14, taxNumber);
        set(15, kpp);
        set(16, originalFailCode);
        set(17, originalRequesterId);
        set(18, billingFileId);
    }
}
