/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hh.jooq.tables.WebDavFile;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WebDavFileRecord extends UpdatableRecordImpl<WebDavFileRecord> implements Record7<Integer, Integer, LocalDateTime, String, String, Boolean, Integer> {

    private static final long serialVersionUID = 1480443971;

    /**
     * Setter for <code>public.web_dav_file.web_dav_file_id</code>.
     */
    public void setWebDavFileId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.web_dav_file.web_dav_file_id</code>.
     */
    public Integer getWebDavFileId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.web_dav_file.parent_id</code>.
     */
    public void setParentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.web_dav_file.parent_id</code>.
     */
    public Integer getParentId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.web_dav_file.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.web_dav_file.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.web_dav_file.file_name</code>.
     */
    public void setFileName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.web_dav_file.file_name</code>.
     */
    public String getFileName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.web_dav_file.extension</code>.
     */
    public void setExtension(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.web_dav_file.extension</code>.
     */
    public String getExtension() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.web_dav_file.is_directory</code>.
     */
    public void setIsDirectory(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.web_dav_file.is_directory</code>.
     */
    public Boolean getIsDirectory() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.web_dav_file.type</code>.
     */
    public void setType(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.web_dav_file.type</code>.
     */
    public Integer getType() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, LocalDateTime, String, String, Boolean, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, LocalDateTime, String, String, Boolean, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return WebDavFile.WEB_DAV_FILE.WEB_DAV_FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return WebDavFile.WEB_DAV_FILE.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field3() {
        return WebDavFile.WEB_DAV_FILE.CREATION_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return WebDavFile.WEB_DAV_FILE.FILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return WebDavFile.WEB_DAV_FILE.EXTENSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return WebDavFile.WEB_DAV_FILE.IS_DIRECTORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return WebDavFile.WEB_DAV_FILE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getWebDavFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value3() {
        return getCreationTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getExtension();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getIsDirectory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebDavFileRecord value1(Integer value) {
        setWebDavFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebDavFileRecord value2(Integer value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebDavFileRecord value3(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebDavFileRecord value4(String value) {
        setFileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebDavFileRecord value5(String value) {
        setExtension(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebDavFileRecord value6(Boolean value) {
        setIsDirectory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebDavFileRecord value7(Integer value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebDavFileRecord values(Integer value1, Integer value2, LocalDateTime value3, String value4, String value5, Boolean value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WebDavFileRecord
     */
    public WebDavFileRecord() {
        super(WebDavFile.WEB_DAV_FILE);
    }

    /**
     * Create a detached, initialised WebDavFileRecord
     */
    public WebDavFileRecord(Integer webDavFileId, Integer parentId, LocalDateTime creationTime, String fileName, String extension, Boolean isDirectory, Integer type) {
        super(WebDavFile.WEB_DAV_FILE);

        set(0, webDavFileId);
        set(1, parentId);
        set(2, creationTime);
        set(3, fileName);
        set(4, extension);
        set(5, isDirectory);
        set(6, type);
    }
}
