/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.routines;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;

import ru.hh.jooq.Public;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FindArea extends AbstractRoutine<Integer> {

    private static final long serialVersionUID = -1527267432;

    /**
     * The parameter <code>public.find_area.RETURN_VALUE</code>.
     */
    public static final Parameter<Integer> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>public.find_area.localized_area_name</code>.
     */
    public static final Parameter<String> LOCALIZED_AREA_NAME = createParameter("localized_area_name", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * Create a new routine call instance
     */
    public FindArea() {
        super("find_area", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER);

        setReturnParameter(RETURN_VALUE);
        addInParameter(LOCALIZED_AREA_NAME);
    }

    /**
     * Set the <code>localized_area_name</code> parameter IN value to the routine
     */
    public void setLocalizedAreaName(String value) {
        setValue(LOCALIZED_AREA_NAME, value);
    }

    /**
     * Set the <code>localized_area_name</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setLocalizedAreaName(Field<String> field) {
        setField(LOCALIZED_AREA_NAME, field);
    }
}
