/*
 * This file is generated by jOOQ.
*/
package ru.hh.jooq.routines;


import javax.annotation.Generated;

import org.jooq.impl.AbstractRoutine;

import ru.hh.jooq.Public;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hh15070CreateBelarusSellerAccount extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -808767305;

    /**
     * Create a new routine call instance
     */
    public Hh15070CreateBelarusSellerAccount() {
        super("hh15070_create_belarus_seller_account", Public.PUBLIC);
    }
}
